# Generated by Django 4.0 on 2021-12-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_id_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='id_index',
        ),
    ]
